### ISSUE TITLE
missing go.sum entry after ran go mod tidy

### ISSUE THREAD

**Issue by jackieli-tes** [google/wire#299]
You can use `go bug` to have a cool, automatically filled out bug template, or
fill out the template below.

### Describe the bug

Following docs, after initial command `wire`, then after `go mod tidy`, subsequent `go generate ./...` reports:

```
/go/pkg/mod/github.com/google/wire@v0.5.0/cmd/wire/main.go:34:2: missing go.sum entry for module providing package github.com/google/subcommands (imported by github.com/google/wire/cmd/wire); to add:
        go get github.com/google/wire/cmd/wire@v0.5.0
/go/pkg/mod/github.com/google/wire@v0.5.0/cmd/wire/main.go:36:2: missing go.sum entry for module providing package github.com/pmezard/go-difflib/difflib (imported by github.com/google/wire/cmd/wire); to add:
        go get github.com/google/wire/cmd/wire@v0.5.0
/go/pkg/mod/github.com/google/wire@v0.5.0/internal/wire/copyast.go:21:2: missing go.sum entry for module providing package golang.org/x/tools/go/ast/astutil (imported by github.com/google/wire/internal/wire); to add:
        go get github.com/google/wire/internal/wire@v0.5.0
/go/pkg/mod/github.com/google/wire@v0.5.0/internal/wire/parse.go:30:2: missing go.sum entry for module providing package golang.org/x/tools/go/packages (imported by github.com/google/wire/internal/wire); to add:
        go get github.com/google/wire/internal/wire@v0.5.0
/go/pkg/mod/github.com/google/wire@v0.5.0/internal/wire/analyze.go:26:2: missing go.sum entry for module providing package golang.org/x/tools/go/types/typeutil (imported by github.com/google/wire/cmd/wire); to add:
        go get github.com/google/wire/cmd/wire@v0.5.0
wire_gen.go:3: running "go": exit status 1
```

### To Reproduce

I use this command to reproduce the problem:

```
docker build - <<EOF
FROM golang
WORKDIR /myproject
RUN go mod init myproject

RUN echo '// +build wireinject' >> wire.go
RUN echo 'package main' >> wire.go
RUN echo 'import ("strings"; "github.com/google/wire")' >> wire.go
RUN echo 'func initReader(s string) *strings.Reader {' >> wire.go
RUN echo '	panic(wire.Build(strings.NewReader))' >> wire.go
RUN echo '}' >> wire.go

RUN go get github.com/google/wire/cmd/wire
RUN wire
RUN cat wire_gen.go
RUN go mod tidy
RUN cat go.mod
RUN go generate ./...
EOF
```

## Expected behavior

`go generate ./...` should run without error

### Version

```
go 1.16

github.com/google/wire v0.5.0
```

### Additional context

Following the error message and run the suggest `go get` commands fixes the problem. But as soon as I run `go mod tidy`, `go generate ./...` reports error

**Comment by drscre** [comment]
Possibly related to https://github.com/golang/go/issues/44129

As a hack, you can run `GOFLAGS=-mod=mod go generate ./...`

**Comment by jackieli-tes** [comment]
> Possibly related to [golang/go#44129](https://github.com/golang/go/issues/44129)
> 
> As a hack, you can run `GOFLAGS=-mod=mod go generate ./...`

I can confirm the workaround working

**Comment by drewolson** [comment]
FWIW, I think the "correct" work-around is to follow the advice [here](https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module) and create a `tools.go` file to track your development-only dependencies. This should resolve the `go.sum` problem and doesn't require setting `GOFLAGS` that introduce potentially unintuitive behavior.

**Comment by ccremer** [comment]
I have the same problem. I do have a `tools.go` file yet the go.sum entry is still missing after `go mod tidy`
```go
// +build tools

// Place any runtime dependencies as imports in this file.
// Go modules will be forced to download and install them.
package tools

import (
	_ "github.com/google/wire"
)
```

**Comment by drewolson** [comment]
> ```go
> // +build tools
> 
> // Place any runtime dependencies as imports in this file.
> // Go modules will be forced to download and install them.
> package tools
> 
> import (
> 	_ "github.com/google/wire"
> )
> ```
> 
> (Go 1.16.7)

I believe this is because you need to be importing `"github.com/google/wire/cmd/wire"`. This is the actual tool you use, not the library.

**Comment by ccremer** [comment]
> you need to be importing "github.com/google/wire/cmd/wire".

Good catch!
This was the culprit, now it works.
Thanks a lot 🎉

**Comment by jackieli-tes** [comment]
Yes, I'm using the `// +build tools` workaround as well

There is some guidelines from here about tracking tools: https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module

And in my case importing `github.com/google/wire/cmd/wire` is enough

**Comment by furuya-kaoru** [comment]
https://github.com/ca-love/server/blob/master/Makefile#L76
も

Go1.18を見越して、
go install 
に変えておいたほうがいいのかな?

**Comment by tx7do** [comment]
add import:

`
package tools

import (
	_ "github.com/google/subcommands"
)
`

then :

`go mod tidy`.

**Comment by manubu1012** [comment]
you can try `go clean --modcache, then `go generate` again
